"""initial

Revision ID: 530bc26727c3
Revises: 
Create Date: 2026-06-20 11:46:44.274393
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '530bc26727c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
